ARG SOURCE_HASH
ARG PORT

FROM alpine:3.7 AS test-base
RUN apk add curl bash

FROM test-base AS test
ARG SOURCE_HASH
ARG PORT
ENV PORT=${PORT}
RUN echo "Source Hash: ${SOURCE_HASH}"
COPY test.sh .
CMD ./test.sh ${PORT}
